.TH "dis::catalan_paths::iterator" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::catalan_paths::iterator \- 
.PP
Forward Iterator for iterating through catalan paths of a certain length\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CatalanPaths\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (nuint n)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "bool \fBis_at_end\fP () const "
.br
.ti -1c
.RI "nuint \fBsize\fP () const "
.br
.ti -1c
.RI "void \fBreset\fP (nuint n)"
.br
.ti -1c
.RI "const VI & \fBoperator*\fP () const "
.br
.ti -1c
.RI "VI & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBcatalan_paths\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Forward Iterator for iterating through catalan paths of a certain length\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
