.TH "dis::subsets::iterator" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::subsets::iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (const \fBsubsets\fP &parent)"
.br
.ti -1c
.RI "\fBiterator\fP (const \fBiterator\fP &it)"
.br
.ti -1c
.RI "\fBiterator\fP (\fBiterator\fP &&it)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const vector< int_fast8_t > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBsubsets\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
