.TH "dis::subsets" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::subsets \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsubsets\fP (nuint size)"
.br
.ti -1c
.RI "\fBsubsets\fP (const vector< int_fast8_t > &total)"
.br
.ti -1c
.RI "size_t \fBsize\fP () const "
.br
.ti -1c
.RI "const \fBiterator\fP & \fBbegin\fP () const "
.br
.ti -1c
.RI "const \fBiterator\fP & \fBend\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
