.TH "dis::MultisetIterator< IntType >" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::MultisetIterator< IntType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultisetIterator\fP (const vector< IntType > &set)"
.br
.ti -1c
.RI "vector< IntType > \fBFirst\fP ()"
.br
.ti -1c
.RI "bool \fBNext\fP (vector< IntType > &subset)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
