.TH "dis::LexicographicOrder< T >" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::LexicographicOrder< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const vector< T > &lhs, const vector< T > &rhs) const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
