.TH "dis::SubsetIterator" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::SubsetIterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubsetIterator\fP (const vector< int_fast8_t > &set)"
.br
.ti -1c
.RI "\fBSubsetIterator\fP (nuint n)"
.br
.ti -1c
.RI "vector< int_fast8_t > \fBFirst\fP ()"
.br
.ti -1c
.RI "bool \fBNext\fP (vector< int_fast8_t > &subset)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
