.TH "dis::multisets< IntType >::iterator" 3 "Sat Nov 21 2015" "Version 1" "Discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dis::multisets< IntType >::iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (const vector< IntType > &total)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const vector< IntType > & \fBoperator*\fP () const "
.br
.ti -1c
.RI "vector< IntType > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBmultisets\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Discreture from the source code\&.
