.TH "dscr::MultisetIteratorDecreasingOrder< IntType >" 3 "Fri Feb 12 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::MultisetIteratorDecreasingOrder< IntType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultisetIteratorDecreasingOrder\fP (const vector< IntType > &total)"
.br
.ti -1c
.RI "vector< IntType > \fBFirst\fP ()"
.br
.ti -1c
.RI "vector< IntType > \fBFirst\fP (nuint numelements)"
.br
.ti -1c
.RI "int \fBNext\fP (vector< IntType > &subset)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
