.TH "dscr::multisets< IntType >" 3 "Wed Feb 10 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::multisets< IntType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmultisets\fP (const vector< IntType > &set)"
.br
.ti -1c
.RI "\fBmultisets\fP (IntType size, IntType n)"
.br
.ti -1c
.RI "const \fBiterator\fP & \fBbegin\fP () const "
.br
.ti -1c
.RI "const \fBiterator\fP & \fBend\fP () const "
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
