.TH "dscr::RClock" 3 "Fri Feb 26 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::RClock \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBRClock\fP & \fBInstance\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::chrono::time_point
.br
< std::chrono::high_resolution_clock > \fBstart_timer\fP"
.br
.ti -1c
.RI "std::chrono::time_point
.br
< std::chrono::high_resolution_clock > \fBrunning_timer\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
