.TH "dscr::basic_multisets< IntType >::iterator" 3 "Sun Feb 28 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::basic_multisets< IntType >::iterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits iterator< std::forward_iterator_tag, vector< IntType > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (const vector< IntType > &total)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const vector< IntType > & \fBoperator*\fP () const "
.br
.ti -1c
.RI "vector< IntType > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_multisets\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
