.TH "dscr::basic_dyck_paths< IntType >::iterator" 3 "Sun Feb 28 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::basic_dyck_paths< IntType >::iterator \- 
.PP
Forward iterator class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DyckPaths\&.hpp>\fP
.PP
Inherits iterator< std::forward_iterator_tag, vector< IntType > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (IntType n)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "const vector< IntType > & \fBoperator*\fP () const "
.br
.ti -1c
.RI "const dyck_path * \fBoperator->\fP () const "
.br
.ti -1c
.RI "size_type \fBID\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBis_at_end\fP (IntType n) const "
.br
.ti -1c
.RI "void \fBreset\fP (IntType r)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBbasic_dyck_paths\fP"
.br
.ti -1c
.RI "difference_type \fBoperator-\fP (const \fBiterator\fP &lhs, const \fBiterator\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class IntType>class dscr::basic_dyck_paths< IntType >::iterator"
Forward iterator class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
