.TH "dscr::partitions" 3 "Wed Feb 10 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::partitions \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBiterator\fP"
.br
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef long int \fBdifference_type\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBsize_type\fP"
.br
.ti -1c
.RI "typedef vector< int > \fBvalue_type\fP"
.br
.ti -1c
.RI "typedef vector< int > \fBpartition\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpartitions\fP (int n)"
.br
.ti -1c
.RI "const \fBiterator\fP & \fBbegin\fP () const "
.br
.ti -1c
.RI "const \fBiterator\fP & \fBend\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static vector< int > \fBconjugate\fP (const vector< int > &P)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
