.TH "dscr::MotzkinPaths::iterator" 3 "Wed Feb 10 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::MotzkinPaths::iterator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (int n)"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "const vector< int > & \fBoperator*\fP () const "
.br
.ti -1c
.RI "vector< int > & \fBoperator*\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const "
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBMotzkinPaths\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
