.TH "dscr::SubsetIterator< BoolType >" 3 "Fri Feb 12 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::SubsetIterator< BoolType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubsetIterator\fP (const vector< BoolType > &set)"
.br
.ti -1c
.RI "\fBSubsetIterator\fP (nuint n)"
.br
.ti -1c
.RI "vector< BoolType > \fBFirst\fP ()"
.br
.ti -1c
.RI "bool \fBNext\fP (vector< BoolType > &subset)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
