.TH "dscr::SubsetIteratorDecreasingOrder< BoolType >" 3 "Fri Feb 12 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dscr::SubsetIteratorDecreasingOrder< BoolType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubsetIteratorDecreasingOrder\fP (nuint n)"
.br
.ti -1c
.RI "VB \fBFirst\fP ()"
.br
.ti -1c
.RI "int \fBNext\fP (VB &subset)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for discreture from the source code\&.
