.TH "todo" 3 "Fri Feb 26 2016" "Version 1" "discreture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBdscr::basic_combinations< IntType >::find_all\fP (PartialPredicate pred)\fP" 1c
Perhaps one should be able to iterate over all such permutations without constructing a vector of them!
.PP

